# Generated by Django 3.0.3 on 2020-02-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooltype',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='tool_pics'),
        ),
    ]
