# Generated by Django 3.0.3 on 2020-03-18 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_auto_20200229_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('reservation_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('checkin_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Tool')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservationlogtools',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservationlogtools',
            name='tool',
        ),
        migrations.DeleteModel(
            name='ReservationLog',
        ),
        migrations.DeleteModel(
            name='ReservationLogTools',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='backend.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
