# Generated by Django 3.0.3 on 2020-03-19 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tooltype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ToolType'),
        ),
    ]
