# Generated by Django 3.0.3 on 2020-03-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200318_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkin_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='checkout_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reservation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
